-- 1. Tabelle für die Empfänger
CREATE TABLE public.recipients (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    facebook_id TEXT UNIQUE NOT NULL,
    name TEXT,
    status TEXT DEFAULT 'pending', -- 'pending', 'active_funnel', 'completed', 'blacklisted'
    
    -- Multi-Account Management
    account_id INTEGER,                           -- ID des Bot-Accounts, der diesen User betreut (1-6)
    
    -- Conversation Funnel State
    conversation_state TEXT DEFAULT 'new',        -- new, msg1_sent, msg1_replied, msg2_sent, msg2_replied, offer_sent, converted, no_reply_24h, blacklisted
    conversation_history TEXT DEFAULT '[]',       -- JSON Array des Chatverlaufs
    reply_received_at TIMESTAMP WITH TIME ZONE,   -- Wann hat der Empfänger zuletzt geschrieben?
    
    -- Phase 1 / Erweiterte Scoring-Metriken
    priority INTEGER DEFAULT 3,                   -- 1: Hoch, 2: Mittel, 3: Niedrig
    person_score INTEGER DEFAULT 0,               -- Engagement Score (ab 40 -> warm)
    common_groups TEXT[],                         -- Array von gemeinsamen Gruppen (z.B. '{"Gruppenname"}')
    common_friends_count INTEGER DEFAULT 0,
    
    last_contact TIMESTAMP WITH TIME ZONE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Index für schnelles Finden von pending records
CREATE INDEX idx_recipients_status ON public.recipients(status);

-- 2. Tabelle für die Message Logs (Erfolgskontrolle)
CREATE TABLE public.message_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    recipient_id TEXT NOT NULL REFERENCES public.recipients(facebook_id) ON DELETE CASCADE,
    variant_id INTEGER NOT NULL,
    content TEXT NOT NULL,
    success BOOLEAN NOT NULL DEFAULT FALSE,
    error_message TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Trigger Function für updated_at
CREATE OR REPLACE FUNCTION update_modified_column() 
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = now();
    RETURN NEW; 
END;
$$ language 'plpgsql';

CREATE TRIGGER update_recipients_modtime
    BEFORE UPDATE ON public.recipients
    FOR EACH ROW
    EXECUTE PROCEDURE update_modified_column();

-- RLS (Row Level Security) für direkten API-Zugriff ohne Auth lockern (in einem reinen Backend-Setup ok, oder strenger via Service Role Key)
ALTER TABLE public.recipients ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.message_logs ENABLE ROW LEVEL SECURITY;

-- Da das Script mit dem anon-Key läuft, erlauben wir Public Access für diesen MVP:
CREATE POLICY "Enable all for authenticated or anon users" ON public.recipients FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Enable all for authenticated or anon users" ON public.message_logs FOR ALL USING (true) WITH CHECK (true);

-- 3. Tabelle für Account Tracking (Always On)
CREATE TABLE public.accounts (
    account_id INTEGER PRIMARY KEY,
    first_login_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    messages_sent_today INTEGER DEFAULT 0,
    last_activity_date DATE DEFAULT CURRENT_DATE,
    login_retries INTEGER DEFAULT 0,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

CREATE TRIGGER update_accounts_modtime
    BEFORE UPDATE ON public.accounts
    FOR EACH ROW
    EXECUTE PROCEDURE update_modified_column();

ALTER TABLE public.accounts ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Enable all for authenticated or anon users" ON public.accounts FOR ALL USING (true) WITH CHECK (true);
